### ISSUE TITLE
errors when running

### ISSUE THREAD

**Issue by provels8467** [orest-d/p4vasp#11]
hi all, 

I got the following problems:

weiweisunsMBP2:bin weiwei$ ./p4v

(process:61698): Gtk-WARNING **: 18:09:01.623: Locale not supported by C library.
	Using the fallback 'C' locale.
2019-04-07 18:09:01.699 Python[61698:10149511] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
/Users/weiwei/p4vasp/python-packages/p4vasp/applet/Applet.py:369: GtkWarning: Cannot open pixbuf loader module file '/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
  Applet.pin_image.set_from_file(path)
/Users/weiwei/p4vasp/python-packages/p4vasp/applet/Applet.py:372: GtkWarning: Cannot open pixbuf loader module file '/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
  Applet.unpin_image.set_from_file(path)
/Users/weiwei/p4vasp/python-packages/p4vasp/applet/Applet.py:376: GtkWarning: Cannot open pixbuf loader module file '/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
  Applet.embedded_image.set_from_file(path)
/Users/weiwei/p4vasp/python-packages/p4vasp/applet/Applet.py:379: GtkWarning: Cannot open pixbuf loader module file '/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
  Applet.external_image.set_from_file(path)
Traceback (most recent call last):
  File "/Users/weiwei/p4vasp/bin/p4v.py", line 225, in createFrame
    xml=p4vasp.util.loadGlade(self.gladefile,self.gladename)
  File "/Users/weiwei/p4vasp/python-packages/p4vasp/util.py", line 494, in loadGlade
    import gtk.glade
ImportError: No module named glade
ERROR : Unable to create Glade object from frame.glade, frame_box
Searching for applets
Creating menu items
Add menu Edit::New
Traceback (most recent call last):
  File "/Users/weiwei/p4vasp/bin/p4v.py", line 640, in idle_func
    scheduler().next()
  File "/Users/weiwei/p4vasp/python-packages/p4vasp/schedule.py", line 51, in next
    return self[0].next()
  File "/Users/weiwei/p4vasp/bin/p4v.py", line 712, in init
    item=frame.getMenuItem(m)
  File "/Users/weiwei/p4vasp/bin/p4v.py", line 317, in getMenuItem
    ch=m.get_children()
AttributeError: 'NoneType' object has no attribute 'get_children'
^CTraceback (most recent call last):
  File "/Users/weiwei/p4vasp/bin/p4v.py", line 763, in <module>
    gtk.main()
KeyboardInterrupt

What do you think?
Thanks a lot!
Weiwei

**Comment by Chengcheng-Xiao** [comment]
1. My local:
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
2. use `brew install gdk-pixbuf` and reinstall p4vasp will probably fix your problem.

Since homebrew updated some of their packages, the installation guide for MacOS needs to be updated as will, I'll get to it as soon as I can.
